import { MatchUser, QuestionnaireAnswers } from "@/types/questionnaire";
import { getAllQuestionIds } from "@/lib/questionnaire/questions";

/**
 * Demo users dataset for matching algorithm
 * Each user has realistic answer patterns to ensure varied match scores
 */

function createAnswers(pattern: Record<string, 1 | 2 | 3 | 4>): QuestionnaireAnswers {
  const allIds = getAllQuestionIds();
  const answers: QuestionnaireAnswers = {};
  
  // Fill in provided answers
  Object.entries(pattern).forEach(([id, value]) => {
    answers[id] = value;
  });
  
  // Fill remaining with neutral (2 or 3) to ensure completeness
  allIds.forEach((id) => {
    if (!answers[id]) {
      answers[id] = Math.random() > 0.5 ? 2 : 3;
    }
  });
  
  return answers;
}

export const DEMO_USERS: MatchUser[] = [
  {
    id: "anna",
    name: "Anna",
    city: "Singapore",
    gender: "Female",
    intent: "Romantic",
    answers: createAnswers({
      q_lifestyle_1: 4, // Strongly agree - large gatherings
      q_lifestyle_2: 1, // Strongly disagree - prefers groups
      q_lifestyle_3: 3,
      q_lifestyle_4: 4,
      q_lifestyle_5: 2,
      q_social_1: 4,
      q_social_2: 2,
      q_social_3: 4,
      q_social_4: 2,
      q_values_1: 4,
      q_values_2: 4,
      q_values_3: 4,
      q_values_4: 3,
      q_comm_1: 3,
      q_comm_2: 4,
      q_comm_3: 3,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "james",
    name: "James",
    city: "Hong Kong",
    gender: "Male",
    intent: "Platonic",
    answers: createAnswers({
      q_lifestyle_1: 2,
      q_lifestyle_2: 4, // Strongly agree - prefers 1:1
      q_lifestyle_3: 4,
      q_lifestyle_4: 3,
      q_lifestyle_5: 4,
      q_social_1: 2,
      q_social_2: 4,
      q_social_3: 2,
      q_social_4: 4,
      q_values_1: 4,
      q_values_2: 3,
      q_values_3: 3,
      q_values_4: 2,
      q_comm_1: 4,
      q_comm_2: 3,
      q_comm_3: 2,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "sarah",
    name: "Sarah",
    city: "Bangkok",
    gender: "Female",
    intent: "Romantic",
    answers: createAnswers({
      q_lifestyle_1: 3,
      q_lifestyle_2: 2,
      q_lifestyle_3: 4,
      q_lifestyle_4: 4,
      q_lifestyle_5: 2,
      q_social_1: 3,
      q_social_2: 3,
      q_social_3: 3,
      q_social_4: 3,
      q_values_1: 4,
      q_values_2: 4,
      q_values_3: 4,
      q_values_4: 4,
      q_comm_1: 2,
      q_comm_2: 4,
      q_comm_3: 4,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "michael",
    name: "Michael",
    city: "Singapore",
    gender: "Male",
    intent: "Professional",
    answers: createAnswers({
      q_lifestyle_1: 4,
      q_lifestyle_2: 1,
      q_lifestyle_3: 2,
      q_lifestyle_4: 3,
      q_lifestyle_5: 1,
      q_social_1: 4,
      q_social_2: 2,
      q_social_3: 4,
      q_social_4: 1,
      q_values_1: 3,
      q_values_2: 3,
      q_values_3: 2,
      q_values_4: 2,
      q_comm_1: 4,
      q_comm_2: 3,
      q_comm_3: 2,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "emma",
    name: "Emma",
    city: "Tokyo",
    gender: "Female",
    intent: "Platonic",
    answers: createAnswers({
      q_lifestyle_1: 1,
      q_lifestyle_2: 4,
      q_lifestyle_3: 4,
      q_lifestyle_4: 2,
      q_lifestyle_5: 4,
      q_social_1: 1,
      q_social_2: 4,
      q_social_3: 1,
      q_social_4: 4,
      q_values_1: 4,
      q_values_2: 4,
      q_values_3: 3,
      q_values_4: 3,
      q_comm_1: 3,
      q_comm_2: 4,
      q_comm_3: 3,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "david",
    name: "David",
    city: "Singapore",
    gender: "Male",
    intent: "Romantic",
    answers: createAnswers({
      q_lifestyle_1: 3,
      q_lifestyle_2: 3,
      q_lifestyle_3: 4,
      q_lifestyle_4: 4,
      q_lifestyle_5: 2,
      q_social_1: 3,
      q_social_2: 3,
      q_social_3: 3,
      q_social_4: 3,
      q_values_1: 4,
      q_values_2: 4,
      q_values_3: 4,
      q_values_4: 3,
      q_comm_1: 2,
      q_comm_2: 4,
      q_comm_3: 4,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "lisa",
    name: "Lisa",
    city: "Bangkok",
    gender: "Female",
    intent: "Platonic",
    answers: createAnswers({
      q_lifestyle_1: 2,
      q_lifestyle_2: 3,
      q_lifestyle_3: 3,
      q_lifestyle_4: 3,
      q_lifestyle_5: 3,
      q_social_1: 3,
      q_social_2: 3,
      q_social_3: 3,
      q_social_4: 3,
      q_values_1: 3,
      q_values_2: 3,
      q_values_3: 3,
      q_values_4: 3,
      q_comm_1: 3,
      q_comm_2: 3,
      q_comm_3: 3,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "robert",
    name: "Robert",
    city: "Hong Kong",
    gender: "Male",
    intent: "Professional",
    answers: createAnswers({
      q_lifestyle_1: 4,
      q_lifestyle_2: 1,
      q_lifestyle_3: 2,
      q_lifestyle_4: 4,
      q_lifestyle_5: 1,
      q_social_1: 4,
      q_social_2: 1,
      q_social_3: 4,
      q_social_4: 1,
      q_values_1: 3,
      q_values_2: 2,
      q_values_3: 2,
      q_values_4: 1,
      q_comm_1: 4,
      q_comm_2: 3,
      q_comm_3: 1,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "sophia",
    name: "Sophia",
    city: "Tokyo",
    gender: "Female",
    intent: "Romantic",
    answers: createAnswers({
      q_lifestyle_1: 1,
      q_lifestyle_2: 4,
      q_lifestyle_3: 4,
      q_lifestyle_4: 3,
      q_lifestyle_5: 4,
      q_social_1: 2,
      q_social_2: 4,
      q_social_3: 1,
      q_social_4: 4,
      q_values_1: 4,
      q_values_2: 4,
      q_values_3: 4,
      q_values_4: 4,
      q_comm_1: 2,
      q_comm_2: 4,
      q_comm_3: 4,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "alex",
    name: "Alex",
    city: "Singapore",
    gender: "Non-binary",
    intent: "Platonic",
    answers: createAnswers({
      q_lifestyle_1: 3,
      q_lifestyle_2: 2,
      q_lifestyle_3: 4,
      q_lifestyle_4: 4,
      q_lifestyle_5: 2,
      q_social_1: 3,
      q_social_2: 3,
      q_social_3: 3,
      q_social_4: 4,
      q_values_1: 4,
      q_values_2: 4,
      q_values_3: 4,
      q_values_4: 4,
      q_comm_1: 3,
      q_comm_2: 4,
      q_comm_3: 4,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "maria",
    name: "Maria",
    city: "Bangkok",
    gender: "Female",
    intent: "Romantic",
    answers: createAnswers({
      q_lifestyle_1: 4,
      q_lifestyle_2: 1,
      q_lifestyle_3: 3,
      q_lifestyle_4: 4,
      q_lifestyle_5: 1,
      q_social_1: 4,
      q_social_2: 2,
      q_social_3: 4,
      q_social_4: 2,
      q_values_1: 4,
      q_values_2: 3,
      q_values_3: 3,
      q_values_4: 3,
      q_comm_1: 4,
      q_comm_2: 3,
      q_comm_3: 3,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "chris",
    name: "Chris",
    city: "Hong Kong",
    gender: "Male",
    intent: "Professional",
    answers: createAnswers({
      q_lifestyle_1: 2,
      q_lifestyle_2: 3,
      q_lifestyle_3: 3,
      q_lifestyle_4: 3,
      q_lifestyle_5: 3,
      q_social_1: 3,
      q_social_2: 3,
      q_social_3: 4,
      q_social_4: 3,
      q_values_1: 3,
      q_values_2: 3,
      q_values_3: 2,
      q_values_4: 2,
      q_comm_1: 3,
      q_comm_2: 3,
      q_comm_3: 2,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "olivia",
    name: "Olivia",
    city: "Tokyo",
    gender: "Female",
    intent: "Platonic",
    answers: createAnswers({
      q_lifestyle_1: 1,
      q_lifestyle_2: 4,
      q_lifestyle_3: 4,
      q_lifestyle_4: 2,
      q_lifestyle_5: 4,
      q_social_1: 1,
      q_social_2: 4,
      q_social_3: 1,
      q_social_4: 4,
      q_values_1: 4,
      q_values_2: 4,
      q_values_3: 3,
      q_values_4: 4,
      q_comm_1: 2,
      q_comm_2: 4,
      q_comm_3: 3,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "daniel",
    name: "Daniel",
    city: "Singapore",
    gender: "Male",
    intent: "Romantic",
    answers: createAnswers({
      q_lifestyle_1: 3,
      q_lifestyle_2: 2,
      q_lifestyle_3: 4,
      q_lifestyle_4: 4,
      q_lifestyle_5: 2,
      q_social_1: 3,
      q_social_2: 3,
      q_social_3: 3,
      q_social_4: 4,
      q_values_1: 4,
      q_values_2: 4,
      q_values_3: 4,
      q_values_4: 3,
      q_comm_1: 2,
      q_comm_2: 4,
      q_comm_3: 4,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "isabella",
    name: "Isabella",
    city: "Bangkok",
    gender: "Female",
    intent: "Platonic",
    answers: createAnswers({
      q_lifestyle_1: 2,
      q_lifestyle_2: 3,
      q_lifestyle_3: 4,
      q_lifestyle_4: 3,
      q_lifestyle_5: 3,
      q_social_1: 2,
      q_social_2: 4,
      q_social_3: 2,
      q_social_4: 4,
      q_values_1: 4,
      q_values_2: 4,
      q_values_3: 3,
      q_values_4: 4,
      q_comm_1: 3,
      q_comm_2: 4,
      q_comm_3: 3,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "william",
    name: "William",
    city: "Hong Kong",
    gender: "Male",
    intent: "Professional",
    answers: createAnswers({
      q_lifestyle_1: 4,
      q_lifestyle_2: 1,
      q_lifestyle_3: 2,
      q_lifestyle_4: 4,
      q_lifestyle_5: 1,
      q_social_1: 4,
      q_social_2: 1,
      q_social_3: 4,
      q_social_4: 1,
      q_values_1: 2,
      q_values_2: 2,
      q_values_3: 1,
      q_values_4: 1,
      q_comm_1: 4,
      q_comm_2: 2,
      q_comm_3: 1,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "mia",
    name: "Mia",
    city: "Tokyo",
    gender: "Female",
    intent: "Romantic",
    answers: createAnswers({
      q_lifestyle_1: 1,
      q_lifestyle_2: 4,
      q_lifestyle_3: 4,
      q_lifestyle_4: 3,
      q_lifestyle_5: 4,
      q_social_1: 2,
      q_social_2: 4,
      q_social_3: 1,
      q_social_4: 4,
      q_values_1: 4,
      q_values_2: 4,
      q_values_3: 4,
      q_values_4: 3,
      q_comm_1: 2,
      q_comm_2: 4,
      q_comm_3: 4,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "ryan",
    name: "Ryan",
    city: "Singapore",
    gender: "Male",
    intent: "Platonic",
    answers: createAnswers({
      q_lifestyle_1: 3,
      q_lifestyle_2: 2,
      q_lifestyle_3: 4,
      q_lifestyle_4: 4,
      q_lifestyle_5: 2,
      q_social_1: 3,
      q_social_2: 3,
      q_social_3: 3,
      q_social_4: 4,
      q_values_1: 4,
      q_values_2: 4,
      q_values_3: 4,
      q_values_4: 4,
      q_comm_1: 3,
      q_comm_2: 4,
      q_comm_3: 4,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "natalie",
    name: "Natalie",
    city: "Bangkok",
    gender: "Female",
    intent: "Romantic",
    answers: createAnswers({
      q_lifestyle_1: 4,
      q_lifestyle_2: 1,
      q_lifestyle_3: 3,
      q_lifestyle_4: 4,
      q_lifestyle_5: 1,
      q_social_1: 4,
      q_social_2: 2,
      q_social_3: 4,
      q_social_4: 2,
      q_values_1: 4,
      q_values_2: 3,
      q_values_3: 3,
      q_values_4: 3,
      q_comm_1: 4,
      q_comm_2: 3,
      q_comm_3: 3,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "ethan",
    name: "Ethan",
    city: "Hong Kong",
    gender: "Male",
    intent: "Professional",
    answers: createAnswers({
      q_lifestyle_1: 2,
      q_lifestyle_2: 3,
      q_lifestyle_3: 3,
      q_lifestyle_4: 3,
      q_lifestyle_5: 3,
      q_social_1: 3,
      q_social_2: 3,
      q_social_3: 4,
      q_social_4: 3,
      q_values_1: 3,
      q_values_2: 3,
      q_values_3: 2,
      q_values_4: 2,
      q_comm_1: 3,
      q_comm_2: 3,
      q_comm_3: 2,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "ava",
    name: "Ava",
    city: "Tokyo",
    gender: "Female",
    intent: "Platonic",
    answers: createAnswers({
      q_lifestyle_1: 1,
      q_lifestyle_2: 4,
      q_lifestyle_3: 4,
      q_lifestyle_4: 2,
      q_lifestyle_5: 4,
      q_social_1: 1,
      q_social_2: 4,
      q_social_3: 1,
      q_social_4: 4,
      q_values_1: 4,
      q_values_2: 4,
      q_values_3: 3,
      q_values_4: 4,
      q_comm_1: 2,
      q_comm_2: 4,
      q_comm_3: 3,
    }),
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "mikhail",
    name: "Mikhail",
    city: "Singapore",
    gender: "Male",
    intent: "Romantic",
    answers: createAnswers({
      q_lifestyle_1: 3,
      q_lifestyle_2: 2,
      q_lifestyle_3: 4,
      q_lifestyle_4: 4,
      q_lifestyle_5: 2,
      q_social_1: 3,
      q_social_2: 3,
      q_social_3: 3,
      q_social_4: 4,
      q_values_1: 4,
      q_values_2: 4,
      q_values_3: 4,
      q_values_4: 3,
      q_comm_1: 2,
      q_comm_2: 4,
      q_comm_3: 4,
    }),
    lastActiveAt: new Date().toISOString(),
  },
];

/**
 * Get default demo user (Mikhail) for fallback
 */
export function getDefaultDemoUser(): MatchUser {
  return DEMO_USERS.find((u) => u.id === "mikhail") || DEMO_USERS[0];
}

